### ISSUE TITLE
Update presentation to include SAML authentication in Connect

### ISSUE THREAD

**Issue by emcrisan** [sol-eng/sys-admin-cheatsheet#4]
The list of available methods does not include SAML, in the Connect Authentication section of the presentation: https://colorado.rstudio.com/rsc/pro-admin-training/configure-connect/03_b_configure_connect.html#19 

It would also be good to include a slide for SAML later in the presentation, as done for the other auth methods.

**Comment by emcrisan** [comment]
I think that this table will also need a SAML column: https://colorado.rstudio.com/rsc/pro-admin-training/configure-connect/03_b_configure_connect.html#24

**Comment by andrie** [comment]
Thanks.  I've fixed this.
